[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "shakeqr"
dynamic = ["version"]
description = "Reorder massively multichannel time series for cross-channel continuity, then learn on the result"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "Scott H. Hawley", email = "scott@scotthawley.com"}]
keywords = ['nbdev']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "torch",
    "numpy",
    "pandas",
    "requests",
    "yfinance",
    "tqdm",
    "matplotlib",
]

[project.optional-dependencies]
dev = [
    "nbdev",
]

[project.urls]
Repository = "https://github.com/drscotthawley/shakeqr"
Documentation = "https://drscotthawley.github.io/shakeqr/"

[project.entry-points.nbdev]
shakeqr = "shakeqr._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "shakeqr.__version__"}

[tool.setuptools.packages.find]
include = ["shakeqr"]

[tool.nbdev]
