# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/shakeqr',
                'doc_host': 'https://drscotthawley.github.io',
                'git_url': 'https://github.com/drscotthawley/shakeqr',
                'lib_path': 'shakeqr'},
  'syms': {'shakeqr.core': {'shakeqr.core.foo': ('core.html#foo', 'shakeqr/core.py')}}}
