"""Downloading NYSE price data and reordering channels for cross-channel continuity.

Docs: https://drscotthawley.github.io/shakeqr/data.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data.ipynb.

# %% auto #0
__all__ = ['DATA_DIR', 'DEVICE', 'ALGOS', 'PAIRINGS', 'get_device', 'get_nyse_data', 'fill_gaps', 'to_returns', 'prepare',
           'build_corr', 'greedy_order', 'spectral_order', 'build_xcorr', 'corr_to_dist', 'build_dist',
           'greedy_edge_order', 'tour_length', 'two_opt', 'tsp_order', 'hrp_order', 'roughness', 'roughness_profile',
           'chain_trace', 'corr_stats', 'standardize', 'log_prices', 'show', 'show_corr', 'show_score_profile',
           'sample_fit_eval', 'run_trial', 'run_benchmark', 'summarize_benchmark']

# %% ../nbs/01_data.ipynb #212974c0
import datetime as dt
import io
import os

import numpy as np
import pandas as pd
import requests
import torch
import yfinance as yf
from tqdm import tqdm

DATA_DIR = "~/github/shakeqr"

# %% ../nbs/01_data.ipynb #52bbbd68
def get_device(prefer=None):
    """cuda -> mps (Apple Silicon) -> cpu, unless `prefer` overrides."""
    if prefer is not None:
        return torch.device(prefer)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


DEVICE = get_device()

# %% ../nbs/01_data.ipynb #7980a6be
def _fetch_nyse_tickers():
    """Strict NYSE (Exchange == 'N'), excluding test issues, preferred-share
    series (the `$` symbols), and warrants/rights/units."""
    url = "https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt"
    resp = requests.get(url, headers={"User-Agent": "Mozilla/5.0"}, timeout=15)
    df = pd.read_csv(io.StringIO(resp.text), sep="|")
    df = df[~df["ACT Symbol"].astype(str).str.contains("File Creation Time", na=False)]
    df = df[~df["ACT Symbol"].str.contains(r"\$", na=False)]
    df = df[df["Exchange"] == "N"]
    df = df[df["Test Issue"] == "N"]
    junk = r"Warrant|Right|Unit|Preferred|Depositary"
    df = df[~df["Security Name"].str.contains(junk, case=False, na=False)]
    return sorted(df["ACT Symbol"].str.strip().str.replace(".", "-", regex=False).tolist())

# %% ../nbs/01_data.ipynb #bc279a65
def get_nyse_data(cache_dir=DATA_DIR, years=4, chunk_size=100, force=False, device=DEVICE):
    """Daily open/close prices for NYSE common stocks plus the S&P 500 index
    prepended as channel 0. Returns `(opening, closing, tickers)` where the
    price tensors are `[channels, days]` and `tickers` is aligned to the
    channel axis. Cached to two `.pt` files; skips the download if present.

    Tensors land on `device` immediately -- the data goes to the GPU as it
    comes off disk, and everything downstream simply inherits it. The `.pt`
    cache is always written from CPU copies so the files stay portable."""
    cache_dir = os.path.expanduser(cache_dir)
    open_path = os.path.join(cache_dir, "nyse_open.pt")
    close_path = os.path.join(cache_dir, "nyse_close.pt")

    if not force and os.path.exists(open_path) and os.path.exists(close_path):
        print(f"Cache hit -- skipping download. (device={device})")
        o, c = torch.load(open_path, weights_only=False), torch.load(close_path, weights_only=False)
        return o["prices"].to(device), c["prices"].to(device), o["tickers"]

    end_date = dt.date.today()
    start_date = end_date - dt.timedelta(days=years * 365)
    tickers = ["^GSPC"] + _fetch_nyse_tickers()
    print(f"Downloading {len(tickers)} tickers from {start_date} to {end_date}...")

    open_chunks, close_chunks = [], []
    for i in tqdm(range(0, len(tickers), chunk_size), desc="downloading batches"):
        batch = tickers[i:i + chunk_size]
        try:
            data = yf.download(batch, start=start_date, end=end_date,
                               group_by="column", progress=False, threads=True)
            if not data.empty:
                open_chunks.append(data["Open"])
                close_chunks.append(data["Close"])
        except Exception as e:
            tqdm.write(f"  batch {i}-{i + chunk_size} failed, skipping: {e}")

    open_df = pd.concat(open_chunks, axis=1).dropna(axis=1, how="all")
    close_df = pd.concat(close_chunks, axis=1).dropna(axis=1, how="all")
    common = open_df.columns.intersection(close_df.columns)
    open_df, close_df = open_df[common].sort_index(), close_df[common].sort_index()

    # .T -> [channels, days]
    open_tensor = torch.tensor(open_df.values.T, dtype=torch.float32)
    close_tensor = torch.tensor(close_df.values.T, dtype=torch.float32)
    tickers = list(common)

    os.makedirs(cache_dir, exist_ok=True)
    torch.save({"tickers": tickers, "prices": open_tensor.cpu()}, open_path)
    torch.save({"tickers": tickers, "prices": close_tensor.cpu()}, close_path)
    print(f"Saved {open_tensor.shape[0]} channels x {open_tensor.shape[1]} days -> {cache_dir}")
    return open_tensor.to(device), close_tensor.to(device), tickers

# %% ../nbs/01_data.ipynb #b68bbbcc
def _ffill(X):
    """Forward-fill NaNs along dim=1."""
    C, T = X.shape
    ar = torch.arange(T, device=X.device).expand(C, T)
    idx = torch.where(~torch.isnan(X), ar, torch.zeros_like(ar))
    return torch.gather(X, 1, torch.cummax(idx, dim=1).values)

# %% ../nbs/01_data.ipynb #1697c777
def fill_gaps(X):
    """Forward- then backward-fill NaNs along time. bfill == ffill reversed.

    Note: back-filling a ticker that didn't exist yet paints its pre-IPO period
    with its first real price -- a convenience, not real history."""
    return _ffill(_ffill(X).flip(1)).flip(1)

# %% ../nbs/01_data.ipynb #ea78e151
def to_returns(opening, closing):
    """`[C, T]` prices -> `[C, T]` intraday returns."""
    return (closing - opening) / opening

# %% ../nbs/01_data.ipynb #4cedc707
def prepare(opening, closing, tickers, min_mean_price=5.0, min_var=1e-12):
    """Fill gaps, drop penny stocks and zero-variance channels.
    Returns `(prices, returns, tickers)`, all mutually aligned. An `assert`
    at the end catches channel/label drift -- otherwise silent, and it's the
    wrong company attributed to every channel with no error raised."""
    opening, closing = fill_gaps(opening), fill_gaps(closing)

    keep = opening.mean(dim=1) >= min_mean_price
    opening, closing = opening[keep], closing[keep]
    tickers = [t for t, k in zip(tickers, keep.tolist()) if k]

    returns = to_returns(opening, closing)
    keep = returns.var(dim=1) > min_var           # else NaN correlations
    opening, returns = opening[keep], returns[keep]
    tickers = [t for t, k in zip(tickers, keep.tolist()) if k]

    assert len(tickers) == opening.shape[0] == returns.shape[0], "channel/ticker drift"
    return opening, returns, tickers

# %% ../nbs/01_data.ipynb #ff0603a6
def build_corr(returns, use_abs=True):
    """`[C, T]` returns -> `[C, C]` Pearson correlation at zero lag."""
    C = torch.nan_to_num(torch.corrcoef(returns.to(torch.float32)), nan=0.0)
    return C.abs() if use_abs else C

# %% ../nbs/01_data.ipynb #b3648c20
def greedy_order(C, start=0):
    """Anchored nearest-neighbour chain. Each step re-anchors on the channel
    just placed, so `start` seeds only the first hop.

    Inherits `C`'s device like everything else. This one is latency-bound
    rather than throughput-bound (N sequential argmaxes, each `int()` forcing
    a sync), so it's the natural candidate for running on CPU instead -- but
    measured at ~2100 channels it's a wash: 18.0 ms CPU vs 18.1 ms CUDA, and
    an explicit round-trip to CPU came out slightly *worse* at 18.8 ms. Not
    worth the special case."""
    N = C.shape[0]
    avail = torch.ones(N, dtype=torch.bool, device=C.device)
    avail[start] = False
    order, cur = [start], start
    for _ in range(N - 1):
        cur = int(torch.argmax(C[cur].masked_fill(~avail, -float("inf"))))
        order.append(cur)
        avail[cur] = False
    return torch.tensor(order, device=C.device)

# %% ../nbs/01_data.ipynb #a393669d
def spectral_order(C, anchor=0, dtype=None):
    """Fiedler-vector seriation of the graph Laplacian L = D - C.

    `dtype=torch.float64` runs the Laplacian and eigendecomposition in double
    precision, which has been found to largely stabilize the result across
    devices. Measured on the same data, CPU vs CUDA: **639/2092 positions
    differ at float32, 6/2092 with float64.** Reaching 0/2092 additionally
    requires `C` itself to be built in float64 -- a float32 correlation
    already differs by ~5e-6 between devices before this function sees it,
    and upcasting can't recover precision that was never computed.

    Why this function specifically, and not the others: the Fiedler
    components sit only ~8.7e-8 apart on average, while a float32 wobble is
    ~1.7e-6 -- roughly 20x the spacing -- so each value sorts past ~20
    neighbours. Note the eigenvector itself is stable (it moves ~2e-6, and
    the Fiedler eigenvalue gap is a healthy 1.76, so this is NOT
    near-degeneracy); it's `argsort` on tightly-packed values that isn't.

    Caveat on interpretation: this buys reproducibility, not meaning.
    Components that close together are ones the method genuinely cannot
    distinguish -- roughness barely moves either way (0.9106 vs 0.9118)."""
    dev = C.device
    if dtype is not None:
        # MPS has no float64; fall back to CPU so the request is still honoured
        C = C.cpu().to(dtype) if (dev.type == "mps" and dtype == torch.float64) else C.to(dtype)
    N = C.shape[0]
    L = torch.diag(C.sum(1)) - C
    _, evecs = torch.linalg.eigh(L)                # ascending eigenvalues
    order = torch.argsort(evecs[:, 1])
    pos = int((order == anchor).nonzero()[0, 0])
    order = order.flip(0) if pos > N // 2 else order
    return order.to(dev)

# %% ../nbs/01_data.ipynb #cb506a16
def build_xcorr(returns, max_lag=20, use_abs=True, device=None):
    """`[C, T]` returns -> `[C, C]` matrix of MAXIMUM cross-correlation-like
    score over shifts `tau` in `[-max_lag, max_lag]` (`build_corr` is the
    `tau=0` special case). `max_lag=None` searches the *entire* timeline
    (`tau` up to `T-1` either direction).

    Each shift's score is divided by the FIXED full series length `T-1`, not
    the shrinking per-shift overlap `n` -- at `tau=0`, `n=T-1` so this is
    exactly the standard correlation; at extreme shifts, the numerator only
    has a handful of terms to sum but still divides by the full `T-1`, so
    the score is naturally discounted toward zero rather than spuriously
    reaching +-1 on a tiny sample the way per-shift normalization would.

    Like `build_dist`, expects **already-whitened** input (unit variance,
    zero mean per channel) -- this scaling only behaves like a correlation
    on whitened data. Whitening happens exactly once, early in the pipeline
    (`returns_w = standardize(returns)`); every downstream function,
    including this one, trusts that single pass rather than re-whitening
    its own input.

    Stays on the input's device by default (pass `device=` to force one).
    It deliberately does NOT copy the result back to CPU -- doing so would
    silently drag the whole downstream pipeline off the GPU."""
    R = returns.to(torch.float32)
    if device is not None:
        R = R.to(device)
    device = R.device
    C, T = R.shape
    max_lag = (T - 1) if max_lag is None else max_lag
    best = torch.zeros(C, C, device=device) if use_abs else torch.full((C, C), -float("inf"), device=device)

    for tau in range(-max_lag, max_lag + 1):
        if tau >= 0:
            a, b = R[:, tau:], R[:, :T - tau]
        else:
            a, b = R[:, :T + tau], R[:, -tau:]
        am = a - a.mean(dim=1, keepdim=True)
        bm = b - b.mean(dim=1, keepdim=True)
        score_tau = (am @ bm.T) / (T - 1)     # fixed denominator, not shrinking n
        best = torch.maximum(best, score_tau.abs()) if use_abs else torch.maximum(best, score_tau)

    return best

# %% ../nbs/01_data.ipynb #d5dcf8fc
def corr_to_dist(C):
    """Generic correlation -> RMS-distance conversion (on whitened data,
    d^2 = 2(1-corr)) -- works for any [C,C] correlation-like matrix, whether
    from `build_corr` (lag 0) or `build_xcorr` (max over lags)."""
    return torch.sqrt((2 * (1 - C)).clamp(min=0))

# %% ../nbs/01_data.ipynb #d2451eeb
def build_dist(returns):
    """`[C, T]` returns -> `[C, C]` RMS distance between channels. The
    zero-lag-specific fast path; see `corr_to_dist` for the generic version.

    Uses float64 for the variance identity (it subtracts two similarly-sized
    terms, so float32 cancellation is measurable) -- except on MPS, which has
    no float64 support at all and would raise; there it falls back to float32
    and eats the precision loss."""
    dtype = torch.float32 if returns.device.type == "mps" else torch.float64
    R = returns.to(dtype)
    mu = R.mean(dim=1)
    var = R.var(dim=1, unbiased=False)
    std = R.std(dim=1, unbiased=False)
    corr = torch.nan_to_num(torch.corrcoef(R), nan=0.0)
    cov = corr * std[:, None] * std[None, :]
    d2 = var[:, None] + var[None, :] - 2 * cov + (mu[:, None] - mu[None, :]) ** 2
    return torch.sqrt(d2.clamp_(min=0)).to(torch.float32)

# %% ../nbs/01_data.ipynb #64857a68
def greedy_edge_order(D):
    """Greedy-edge TSP construction (Kruskal-style union-find)."""
    N = D.shape[0]
    iu = torch.triu_indices(N, N, offset=1)
    w = D[iu[0], iu[1]]
    order_idx = torch.argsort(w).tolist()
    ii, jj = iu[0].tolist(), iu[1].tolist()

    parent = list(range(N))
    def find(x):
        r = x
        while parent[r] != r:
            r = parent[r]
        while parent[x] != r:
            parent[x], x = r, parent[x]
        return r

    deg = [0] * N
    adj = [[] for _ in range(N)]
    n_edges = 0
    for e in order_idx:
        i, j = ii[e], jj[e]
        if deg[i] >= 2 or deg[j] >= 2:
            continue
        ri, rj = find(i), find(j)
        if ri == rj:
            continue
        parent[ri] = rj
        adj[i].append(j); adj[j].append(i)
        deg[i] += 1; deg[j] += 1
        n_edges += 1
        if n_edges == N - 1:
            break

    start = next((v for v in range(N) if deg[v] < 2), 0)
    path, prev, cur = [start], -1, start
    while len(path) < N:
        nxt = next(v for v in adj[cur] if v != prev)
        path.append(nxt); prev, cur = cur, nxt
    return torch.tensor(path, device=D.device)

# %% ../nbs/01_data.ipynb #6538195b
def tour_length(D, order):
    """Total length of an open-path tour -- the quantity 2-opt minimizes."""
    return D[order[:-1], order[1:]].sum().item()

# %% ../nbs/01_data.ipynb #154cbd8b
def two_opt(D, order, max_passes=30, tol=1e-9):
    """Full vectorized 2-opt on an open path, via the standard trick of
    closing it into a cycle through a zero-cost phantom node."""
    N = len(order)
    device = D.device
    Dc = torch.zeros(N + 1, N + 1, device=device)
    Dc[:N, :N] = D
    order = torch.cat([order, torch.tensor([N], device=device)])

    for _ in range(max_passes):
        M = N + 1
        Dp = Dc[order][:, order]
        edge = torch.arange(M - 1, device=device)
        d_cur = Dp[edge, edge + 1]

        a = edge.view(-1, 1)
        b = edge.view(1, -1)
        delta = Dp[a, b] + Dp[(a + 1).clamp(max=M - 1), (b + 1).clamp(max=M - 1)]                 - d_cur.view(-1, 1) - d_cur.view(1, -1)
        valid = (b > a + 1) & (b < M - 1)
        delta = torch.where(valid, delta, torch.full_like(delta, float("inf")))

        best = torch.argmin(delta)
        width = delta.shape[1]          # delta is (M-1, M-1), NOT (M, M)
        bi, bj = best // width, best % width
        if delta[bi, bj] >= -tol:
            break
        order[bi + 1:bj + 1] = order[bi + 1:bj + 1].flip(0)

    order = order[order != N]           # drop the phantom node
    return order

# %% ../nbs/01_data.ipynb #a2191842
def tsp_order(returns, max_passes=30):
    """Greedy-edge construction + 2-opt refinement, targeting `roughness`
    directly rather than correlation. Zero-lag only (uses `build_dist`); for
    the cross-correlation metric, build `D` via `corr_to_dist(build_xcorr(...))`
    and call `two_opt(D, greedy_edge_order(D))` directly. Returns `(order, D)`."""
    D = build_dist(returns)
    order = two_opt(D, greedy_edge_order(D), max_passes=max_passes)
    return order, D

# %% ../nbs/01_data.ipynb #ff826987
def hrp_order(D):
    """HRP-style quasi-diagonalization: the leaf order of a single-linkage
    dendrogram. Same `(D)` signature as `greedy_edge_order`."""
    N = D.shape[0]
    if N == 1:
        return torch.zeros(1, dtype=torch.long, device=D.device)
    iu = torch.triu_indices(N, N, offset=1)
    w = D[iu[0], iu[1]]
    order_idx = torch.argsort(w).tolist()
    ii, jj = iu[0].tolist(), iu[1].tolist()

    parent = list(range(N))
    def find(x):
        r = x
        while parent[r] != r:
            r = parent[r]
        while parent[x] != r:
            parent[x], x = r, parent[x]
        return r

    children = {}                 # internal node id -> (left, right)
    node_of = list(range(N))      # union-find root -> its dendrogram node id
    next_node, n_merges = N, 0
    for e in order_idx:
        ri, rj = find(ii[e]), find(jj[e])
        if ri == rj:
            continue
        children[next_node] = (node_of[ri], node_of[rj])
        parent[ri] = rj           # rj becomes the new union-find root
        node_of[rj] = next_node
        next_node += 1
        n_merges += 1
        if n_merges == N - 1:
            break

    order, stack = [], [next_node - 1]      # DFS from the final merge (root)
    while stack:
        n = stack.pop()
        if n < N:
            order.append(n)
        else:
            l, r = children[n]
            stack.append(r)                  # push right first -> left pops first
            stack.append(l)
    return torch.tensor(order, device=D.device)

# %% ../nbs/01_data.ipynb #192b8da4
def roughness(X, order=None):
    """Mean total variation between adjacent channels. Lower = smoother."""
    Y = X if order is None else X[order]
    return (Y[1:] - Y[:-1]).abs().mean().item()

# %% ../nbs/01_data.ipynb #f81e5604
def roughness_profile(X, order, n_blocks=10):
    """Per-position roughness -- reveals non-uniformity that the mean hides."""
    d = (X[order][1:] - X[order][:-1]).abs().mean(dim=1)
    return [b.mean().item() for b in torch.tensor_split(d, n_blocks)]

# %% ../nbs/01_data.ipynb #250426ef
def chain_trace(C, order, tickers, n=8):
    """Print the pairs the chain actually maximized, hop by hop."""
    o = order.tolist()
    for k in range(min(n, len(o) - 1)):
        print(f"ch {k:2d} -> {k+1:2d}: {C[o[k], o[k+1]]:.3f}   "
              f"{tickers[o[k]]} -> {tickers[o[k+1]]}")

# %% ../nbs/01_data.ipynb #c165d3a1
def corr_stats(C, orders):
    """`orders`: dict of name -> order tensor."""
    off = C.clone().fill_diagonal_(0)
    print(f"mean |corr|:      {off.mean():.3f}")
    print(f"max off-diagonal: {off.max():.3f}")
    print(f"S&P best match:   {off[0].max():.3f}   (first hop only)")
    for name, o in orders.items():
        adj = C[o[:-1], o[1:]]
        print(f"{name:9s} adjacent corr -- mean {adj.mean():.3f}, "
              f"first10 {adj[:10].mean():.3f}, last10 {adj[-10:].mean():.3f}")

# %% ../nbs/01_data.ipynb #b71a0144
def standardize(X, eps=1e-8):
    """Zero mean, unit variance per channel (along time)."""
    return (X - X.mean(dim=1, keepdim=True)) / (X.std(dim=1, keepdim=True) + eps)

# %% ../nbs/01_data.ipynb #05baff29
def log_prices(prices):
    """Standardized log-prices. `clamp_min` guards against a stray zero or
    negative price, which would give -inf and NaN out the whole channel."""
    return standardize(torch.log(prices.clamp_min(0.01)))

# %% ../nbs/01_data.ipynb #a73a60e1
def _two_panel(x, y, Z, title, xlabel, ylabel, zlabel, cmap="viridis"):
    """Heatmap (top-down) + 3D surface, side by side. Rasterized: fixed
    small output size regardless of grid size, at the cost of no live
    rotation. Relies on `%matplotlib inline` (set once, notebook-side) for
    display -- returning the Figure directly, the idiomatic Jupyter way."""
    import matplotlib.pyplot as plt

    fig = plt.figure(figsize=(12, 5))
    fig.suptitle(title)

    ax1 = fig.add_subplot(1, 2, 1)
    im = ax1.imshow(Z, aspect="auto", cmap=cmap,
                     extent=[x[0], x[-1], y[-1], y[0]])
    ax1.set_xlabel(xlabel); ax1.set_ylabel(ylabel)
    fig.colorbar(im, ax=ax1, shrink=0.8)

    ax2 = fig.add_subplot(1, 2, 2, projection="3d")
    Xg, Yg = np.meshgrid(x, y)
    ax2.plot_surface(Xg, Yg, Z, cmap=cmap, linewidth=0, antialiased=False)
    ax2.set_xlabel(xlabel); ax2.set_ylabel(ylabel); ax2.set_zlabel(zlabel)

    plt.tight_layout()
    plt.close(fig)   # prevent %matplotlib inline's auto-capture from also
                      # displaying it -- otherwise it renders twice (once via
                      # this return value, once via the inline auto-hook)
    return fig

# %% ../nbs/01_data.ipynb #a04df9a7
def show(X, title, n_ch=None, t_stride=5, clip=3.0, cmap="viridis"):
    """Two static views over ALL channels by default (`n_ch=None`); x is in
    real days. `t_stride` controls point density on the day axis."""
    n_ch = X.shape[0] if n_ch is None else n_ch
    Z = X[:n_ch, ::t_stride].clamp(-clip, clip).cpu().numpy()
    x = np.arange(X.shape[1])[::t_stride]
    y = np.arange(Z.shape[0])
    return _two_panel(x, y, Z, title, "day", "channel", "value", cmap=cmap)

# %% ../nbs/01_data.ipynb #43a9698e
def show_corr(C, order, title, n=None, cmap="viridis"):
    """Correlation matrix permuted by `order` -- banded means it worked.
    ALL channels by default (`n=None`). Diagonal (self-correlation, always
    exactly 1) is masked to NaN -- it's trivial and dominates the color/
    height scale otherwise; NaN reads as "excluded," not as a real value
    the way 0 would."""
    n = len(order) if n is None else n
    o = order[:n]
    Z = C[o][:, o].cpu().numpy()
    np.fill_diagonal(Z, np.nan)
    idx = np.arange(len(o))
    return _two_panel(idx, idx, Z, title, "channel", "channel", "corr", cmap=cmap)

# %% ../nbs/01_data.ipynb #bc0c3b56
def show_score_profile(C, orders, title="pairing score by position", sort_desc=False):
    """Stacked subplots, one row per ordering, of `C[o[:-1], o[1:]]` (score
    vs. immediate predecessor). Default: plotted in positional order (as
    encountered walking the ordering) -- shows *where* quality holds up or
    collapses. `sort_desc=True` instead sorts each ordering's own scores
    independently from highest to lowest -- most-correlated-left,
    least-correlated-right -- decoupled from position, useful for a clean
    side-by-side of how gently or sharply each method's quality decays
    overall. `orders`: dict of name -> order tensor, same convention as
    `corr_stats`. Each row gets its own color from the standard cycle (each
    Axes otherwise resets to color 0 independently, so every row would
    default to the same blue)."""
    import matplotlib.pyplot as plt
    n = len(orders)
    colors = plt.rcParams["axes.prop_cycle"].by_key()["color"]
    fig, axes = plt.subplots(n, 1, figsize=(10, 2.5 * n), sharex=True)
    axes = [axes] if n == 1 else axes
    for i, (ax, (name, o)) in enumerate(zip(axes, orders.items())):
        adj = C[o[:-1], o[1:]].cpu().numpy()
        if sort_desc:
            adj = np.sort(adj)[::-1]
        ax.plot(np.arange(1, len(adj) + 1), adj, linewidth=1, color=colors[i % len(colors)])
        ax.set_ylabel(name)
    axes[-1].set_xlabel("rank (best to worst)" if sort_desc else "position (channel index in ordering)")
    fig.suptitle(title)
    plt.tight_layout()
    plt.close(fig)
    return fig

# %% ../nbs/01_data.ipynb #d0dc81bb
ALGOS = {
    "greedy":   lambda C, D: greedy_order(C, start=0),
    "spectral": lambda C, D: spectral_order(C, anchor=0),
    "tsp":      lambda C, D: two_opt(D, greedy_edge_order(D)),
    "hrp":      lambda C, D: hrp_order(D),
}
PAIRINGS = ["corr", "xcorr"]

# %% ../nbs/01_data.ipynb #2387857f
def sample_fit_eval(T, min_len, max_len, rng, min_eval=60):
    """Pick a random contiguous fit window, plus a DISJOINT eval window taken
    from whatever timeline remains on either side. Returns
    `((fit_start, fit_end), (eval_start, eval_end) or None)`."""
    L = int(rng.integers(min_len, max_len + 1))
    start = int(rng.integers(0, T - L + 1))
    fit = (start, start + L)
    segs = [s for s in ((0, start), (start + L, T)) if s[1] - s[0] >= min_eval]
    if not segs:
        return fit, None
    lo, hi = segs[int(rng.integers(0, len(segs)))]
    Le = min(L, hi - lo)
    es = int(rng.integers(lo, hi - Le + 1))
    return fit, (es, es + Le)

# %% ../nbs/01_data.ipynb #65794ba6
def run_trial(returns, rng, min_len=120, max_len=None, xcorr_max_lag=20, min_var=1e-12):
    """One trial: crop a fit window, build all 6 (pairing, algo) orderings on
    it, and score each by roughness both in-sample and on a disjoint window.
    Channels degenerate *within this window* are dropped -- the same channel
    set is used for every combo, so the comparison stays paired."""
    T = returns.shape[1]
    max_len = max_len or int(0.8 * T)
    (fs, fe), ev = sample_fit_eval(T, min_len, max_len, rng)

    Rfit = returns[:, fs:fe]
    keep = Rfit.var(dim=1) > min_var
    Rfit = standardize(Rfit[keep])
    Rev = standardize(returns[keep][:, ev[0]:ev[1]]) if ev else None

    out = {}
    for pairing in PAIRINGS:
        C = build_corr(Rfit) if pairing == "corr" else build_xcorr(Rfit, max_lag=xcorr_max_lag)
        D = corr_to_dist(C)
        for algo, fn in ALGOS.items():
            order = fn(C, D)
            out[(pairing, algo)] = {
                "in_sample": roughness(Rfit, order),
                "held_out": roughness(Rev, order) if Rev is not None else float("nan"),
            }
    out["_meta"] = {"fit_len": fe - fs, "eval_len": (ev[1] - ev[0]) if ev else 0,
                    "n_channels": int(keep.sum())}
    return out

# %% ../nbs/01_data.ipynb #56c0c906
def run_benchmark(returns, n_trials=20, results=None, seed=None, min_len=120,
                   max_len=None, xcorr_max_lag=20, progress=True):
    """Run `n_trials` independent trials, appending to `results` so the
    benchmark is resumable -- call it again with the same list to keep
    accumulating rather than starting over."""
    results = [] if results is None else results
    rng = np.random.default_rng(seed)
    it = tqdm(range(n_trials), desc="benchmark trials") if progress else range(n_trials)
    for _ in it:
        results.append(run_trial(returns, rng, min_len=min_len, max_len=max_len,
                                  xcorr_max_lag=xcorr_max_lag))
    return results

# %% ../nbs/01_data.ipynb #432fa526
def summarize_benchmark(results, metric="held_out", verbose=True):
    """Weighted-mean roughness (weight = fit-window length) and win rate per
    combo, ranked best-first. Returns a list of dicts."""
    combos = [k for k in results[0] if k != "_meta"]
    w_all = np.array([r["_meta"]["fit_len"] for r in results], dtype=float)

    rows = []
    for combo in combos:
        vals = np.array([r[combo][metric] for r in results], dtype=float)
        ok = ~np.isnan(vals)
        v, w = vals[ok], w_all[ok]
        if len(v) == 0:
            continue
        wmean = float((v * w).sum() / w.sum())
        # standard error of a weighted mean (weights treated as known)
        se = float(np.sqrt((w ** 2 * (v - wmean) ** 2).sum()) / w.sum())
        rows.append({"pairing": combo[0], "algo": combo[1], "mean": wmean,
                      "se": se, "n": int(ok.sum()), "wins": 0})

    # win rate: per trial, who had the lowest score -- a paired comparison,
    # so it is not distorted by some windows simply being harder than others
    for r in results:
        scored = [(c, r[c][metric]) for c in combos if not np.isnan(r[c][metric])]
        if not scored:
            continue
        best = min(scored, key=lambda t: t[1])[0]
        for row in rows:
            if (row["pairing"], row["algo"]) == best:
                row["wins"] += 1

    n_trials = len(results)
    for row in rows:
        row["win_rate"] = row["wins"] / n_trials if n_trials else float("nan")
    rows.sort(key=lambda d: d["mean"])

    if verbose:
        print(f"metric={metric!r}, {n_trials} trials  (lower roughness = better)\n")
        print(f"{'pairing':8s} {'algo':9s} {'weighted mean':>14s} {'+/- se':>9s} {'win rate':>9s}")
        for row in rows:
            print(f"{row['pairing']:8s} {row['algo']:9s} {row['mean']:14.5f} "
                  f"{row['se']:9.5f} {row['win_rate']:9.1%}")
        if len(rows) >= 2:
            a, b = rows[0], rows[1]
            gap = b["mean"] - a["mean"]
            pooled = float(np.hypot(a["se"], b["se"]))
            verdict = "clear" if gap > 2 * pooled else "NOT yet separated -- run more trials"
            print(f"\nbest: {a['pairing']}/{a['algo']}  "
                  f"(gap to runner-up {gap:.5f}, ~{gap / pooled:.1f} se) -> {verdict}")
    return rows
