"""Parameterized hypercomplex layers over the views axis, and a first
representation-learning model on the `[views, channels, days]` array.

Docs: https://drscotthawley.github.io/shakeqr/hypercomplex.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_hypercomplex.ipynb.

# %% auto #0
__all__ = ['GRASSUCCI_LICENSE', 'ph_weight', 'hamilton_basis', 'PHMLinear', 'PHConv1d', 'count_params', 'ConvAE1d', 'make_ae',
           'ph_algebras', 'views_to_batch', 'fit_ae', 'algebra_stats', 'show_algebra']

# %% ../nbs/03_hypercomplex.ipynb #7e900c10
# The PH layers in this module are a re-implementation following
# E. Grassucci et al., "HyperNets: Hypercomplex Neural Networks with PyTorch",
# https://github.com/eleGAN23/HyperNets -- released under the MIT License:
GRASSUCCI_LICENSE = """
MIT License

Copyright (c) 2021 Eleonora Grassucci

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import math

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

# %% ../nbs/03_hypercomplex.ipynb #cdfd424b
def ph_weight(A, S):
    """`A: [n, n, n]`, `S: [n, out/n, in/n, *kernel]` -> `W: [out, in, *kernel]`
    with `W = sum_i kron(A[i], S[i])` (kernel dims ride along)."""
    n, o, i = S.shape[:3]
    W = torch.einsum("nab,ncd...->acbd...", A, S)      # [n, o, n, i, *k]
    return W.reshape(n * o, n * i, *S.shape[3:])


def hamilton_basis():
    """The four `[4, 4]` matrices of left-multiplication by `1, i, j, k`. With
    `A = hamilton_basis()` a PH layer *is* a quaternion layer."""
    return torch.tensor([
        [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]],
        [[0, -1, 0, 0], [1, 0, 0, 0], [0, 0, 0, -1], [0, 0, 1, 0]],
        [[0, 0, -1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, -1, 0, 0]],
        [[0, 0, 0, -1], [0, 0, -1, 0], [0, 1, 0, 0], [1, 0, 0, 0]],
    ], dtype=torch.float32)

# %% ../nbs/03_hypercomplex.ipynb #80b76102
class PHMLinear(nn.Module):
    """Parameterized hypercomplex linear layer: `W = sum_i kron(A_i, S_i)`."""
    def __init__(self, n, in_features, out_features, bias=True):
        super().__init__()
        assert in_features % n == 0 and out_features % n == 0, "features must be multiples of n"
        self.n, self.in_features, self.out_features = n, in_features, out_features
        self.A = nn.Parameter(nn.init.xavier_uniform_(torch.empty(n, n, n)))
        self.S = nn.Parameter(torch.empty(n, out_features // n, in_features // n))
        self.bias = nn.Parameter(torch.empty(out_features)) if bias else None
        self.reset_parameters()

    def reset_parameters(self):
        bound = 1 / math.sqrt(self.in_features)
        nn.init.uniform_(self.S, -bound, bound)
        if self.bias is not None:
            nn.init.uniform_(self.bias, -bound, bound)

    @property
    def weight(self):
        return ph_weight(self.A, self.S)

    def forward(self, x):
        return F.linear(x, self.weight, self.bias)

    def extra_repr(self):
        return f"n={self.n}, in_features={self.in_features}, out_features={self.out_features}"


class PHConv1d(nn.Module):
    """Parameterized hypercomplex 1-D convolution, same signature as
    `nn.Conv1d` with `n` in front."""
    def __init__(self, n, in_channels, out_channels, kernel_size, stride=1, padding=0,
                 dilation=1, bias=True):
        super().__init__()
        assert in_channels % n == 0 and out_channels % n == 0, "channels must be multiples of n"
        self.n, self.in_channels, self.out_channels = n, in_channels, out_channels
        self.kernel_size, self.stride, self.padding, self.dilation = kernel_size, stride, padding, dilation
        self.A = nn.Parameter(nn.init.xavier_uniform_(torch.empty(n, n, n)))
        self.S = nn.Parameter(torch.empty(n, out_channels // n, in_channels // n, kernel_size))
        self.bias = nn.Parameter(torch.empty(out_channels)) if bias else None
        self.reset_parameters()

    def reset_parameters(self):
        bound = 1 / math.sqrt(self.in_channels * self.kernel_size)
        nn.init.uniform_(self.S, -bound, bound)
        if self.bias is not None:
            nn.init.uniform_(self.bias, -bound, bound)

    @property
    def weight(self):
        return ph_weight(self.A, self.S)

    def forward(self, x):
        return F.conv1d(x, self.weight, self.bias, stride=self.stride, padding=self.padding,
                        dilation=self.dilation)

    def extra_repr(self):
        return (f"n={self.n}, {self.in_channels}, {self.out_channels}, kernel_size={self.kernel_size}, "
                f"stride={self.stride}, padding={self.padding}")


def count_params(m):
    return sum(p.numel() for p in m.parameters() if p.requires_grad)

# %% ../nbs/03_hypercomplex.ipynb #4a27aa1e
class ConvAE1d(nn.Module):
    """Strided conv encoder / upsampling decoder along the last axis.
    `conv(in, out, k, **kw)` is the layer factory, so PH and real versions
    share one definition."""
    def __init__(self, conv, f_in, h, z, k=5):
        super().__init__()
        p = k // 2
        self.enc = nn.Sequential(
            conv(f_in, h, k, padding=p), nn.GELU(),
            conv(h, h, k, stride=2, padding=p), nn.GELU(),
            conv(h, z, 1))
        self.dec = nn.Sequential(
            conv(z, h, 1), nn.GELU(),
            conv(h, h, k, padding=p), nn.GELU(),
            conv(h, f_in, k, padding=p))

    def encode(self, x):
        return self.enc(x)

    def decode(self, z, length):
        return self.dec(F.interpolate(z, size=length, mode="nearest"))

    def forward(self, x):
        return self.decode(self.encode(x), x.shape[-1])


def make_ae(n, f, h, z, k=5, hyper=True):
    """`[B, n*f, C]` autoencoder. `hyper=True`: every conv is a `PHConv1d`
    with `n` views; `False`: plain `nn.Conv1d` at the same widths (the
    baseline). Widths `h`, `z` are per view, so the tensors are `n*h`, `n*z`."""
    if hyper:
        conv = lambda i, o, k, **kw: PHConv1d(n, i, o, k, **kw)
    else:
        conv = lambda i, o, k, **kw: nn.Conv1d(i, o, k, **kw)
    return ConvAE1d(conv, n * f, n * h, n * z, k)


def ph_algebras(model):
    """All learned `A` tensors in a model, in module order: `[n_layers, n, n, n]`."""
    return torch.stack([m.A.detach() for m in model.modules() if isinstance(m, (PHConv1d, PHMLinear))])

# %% ../nbs/03_hypercomplex.ipynb #17427e1d
def views_to_batch(V):
    """`[n, C, T]` -> `[T, n, C]`; `[n, C, P, T]` -> `[T, n*P, C]` (view-major
    features). Days become the batch axis, channel position the conv axis."""
    if V.ndim == 3:
        return V.permute(2, 0, 1).contiguous()
    n, C, P, T = V.shape
    return V.permute(3, 0, 2, 1).reshape(T, n * P, C).contiguous()


def fit_ae(model, X, epochs=30, lr=2e-3, batch_size=64, val_frac=0.2, weight_decay=1e-4,
           verbose=True, seed=0):
    """Train `model` to reconstruct `X` (`[T, F, C]`), last `val_frac` of the
    time axis held out. Returns `{"train": [...], "val": [...]}` per epoch."""
    device = X.device
    model = model.to(device)
    T = X.shape[0]
    n_val = max(1, int(round(val_frac * T)))
    Xtr, Xva = X[:T - n_val], X[T - n_val:]
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    g = torch.Generator().manual_seed(seed)
    hist = {"train": [], "val": []}
    for ep in range(epochs):
        model.train()
        perm = torch.randperm(Xtr.shape[0], generator=g)
        tot, cnt = 0.0, 0
        for i in range(0, len(perm), batch_size):
            xb = Xtr[perm[i:i + batch_size]]
            loss = F.mse_loss(model(xb), xb)
            opt.zero_grad(set_to_none=True); loss.backward(); opt.step()
            tot += loss.item() * xb.shape[0]; cnt += xb.shape[0]
        model.eval()
        with torch.no_grad():
            val = float(np.mean([F.mse_loss(model(Xva[i:i + batch_size]), Xva[i:i + batch_size]).item()
                                 for i in range(0, Xva.shape[0], batch_size)]))
        hist["train"].append(tot / cnt); hist["val"].append(val)
        if verbose and (ep % max(1, epochs // 10) == 0 or ep == epochs - 1):
            print(f"epoch {ep:3d}  train {tot / cnt:.4f}  val {val:.4f}")
    return hist

# %% ../nbs/03_hypercomplex.ipynb #2f908e73
def algebra_stats(A):
    """`A: [n, n, n]` -> dict of asymmetry per component and the normalized
    Gram matrix between components."""
    A = A.detach().float()
    fro = A.flatten(1).norm(dim=1).clamp_min(1e-8)
    asym = (A - A.transpose(1, 2)).flatten(1).norm(dim=1) / fro
    An = A.flatten(1) / fro[:, None]
    return {"asymmetry": asym.cpu(), "gram": (An @ An.T).cpu()}


def show_algebra(A, title="learned algebra", cmap="RdBu_r"):
    """One panel per `A_i`, symmetric colour scale, plus the Gram matrix."""
    import matplotlib.pyplot as plt
    A = A.detach().float().cpu()
    n = A.shape[0]
    st = algebra_stats(A)
    fig, axes = plt.subplots(1, n + 1, figsize=(2.6 * (n + 1), 2.8))
    v = A.abs().max().item()
    for i, ax in enumerate(axes[:n]):
        ax.imshow(A[i].numpy(), cmap=cmap, vmin=-v, vmax=v)
        ax.set_title(f"A_{i}  asym {st['asymmetry'][i]:.2f}", fontsize=9)
        ax.set_xticks([]); ax.set_yticks([])
    im = axes[-1].imshow(st["gram"].numpy(), cmap=cmap, vmin=-1, vmax=1)
    axes[-1].set_title("Gram <A_i, A_j>", fontsize=9)
    axes[-1].set_xticks([]); axes[-1].set_yticks([])
    fig.colorbar(im, ax=axes[-1], shrink=0.8)
    fig.suptitle(title)
    plt.tight_layout()
    plt.close(fig)
    return fig
