"""Wavelet scattering along the time axis, in plain torch.

Docs: https://drscotthawley.github.io/shakeqr/scattering.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_scattering.ipynb.

# %% auto #0
__all__ = ['morlet_hat', 'gauss_hat', 'morlet_params', 'morlet_bank', 'get_bank', 'wavelet_transform', 'scattering_paths',
           'scattering', 'scattering_features', 'scattering_corr', 'show_scattergram', 'stack_views']

# %% ../nbs/02_scattering.ipynb #3cfed920
import math

import numpy as np
import torch

# %% ../nbs/02_scattering.ipynb #e59170ed
def _gauss_hat(freqs, sigma):
    return torch.exp(-freqs ** 2 / (2 * sigma ** 2))


def _periodize(h, nperiods):
    """Fold a Fourier-domain filter evaluated over `nperiods` periods back
    onto one period: `v[k] = mean_i h[i*N + k]`."""
    N = h.shape[-1] // nperiods
    return h.reshape(*h.shape[:-1], nperiods, N).mean(dim=-2)


def _l1_normalize(h_hat):
    """Scale so the filter's time-domain L1 norm is 1."""
    h = torch.fft.ifft(h_hat)
    return h_hat / h.abs().sum(dim=-1, keepdim=True)


def morlet_hat(N, xi, sigma, eps=1e-7):
    """Fourier transform of one L1-normalized Morlet wavelet on `N` samples,
    at the frequencies `torch.fft.fftfreq(N)`. `xi`, `sigma` in cycles/sample."""
    P = int(math.ceil(math.sqrt(-2 * sigma ** 2 * math.log(eps)) + 1))
    freqs = torch.arange((1 - P) * N, P * N, dtype=torch.float64) / N
    gabor = _periodize(_gauss_hat(freqs - xi, sigma), 2 * P - 1)
    low = _periodize(_gauss_hat(freqs, sigma), 2 * P - 1)
    kappa = gabor[0] / low[0]
    return _l1_normalize(gabor - kappa * low)


def gauss_hat(N, sigma, eps=1e-7):
    """Fourier transform of an L1-normalized Gaussian low-pass on `N` samples."""
    P = int(math.ceil(math.sqrt(-2 * sigma ** 2 * math.log(eps)) + 1))
    freqs = torch.arange((1 - P) * N, P * N, dtype=torch.float64) / N
    return _l1_normalize(_periodize(_gauss_hat(freqs, sigma), 2 * P - 1))

# %% ../nbs/02_scattering.ipynb #6e79d7ec
def morlet_params(J, Q=1, high_freq=0.425, r=math.sqrt(0.5)):
    """Centre frequencies `xi` and bandwidths `sigma` for `J*Q` Morlet
    wavelets, `Q` per octave, from `high_freq` down. Adjacent filters cross
    at fraction `r` of their peak (kymatio's rule)."""
    xi = high_freq * 2.0 ** (-torch.arange(J * Q, dtype=torch.float64) / Q)
    factor = 2.0 ** (-1.0 / Q)
    sigma = xi * (1 - factor) / (1 + factor) / math.sqrt(2 * math.log(1 / r))
    return xi, sigma


def morlet_bank(N, J, Q=1, high_freq=0.425, device=None):
    """`[J*Q + 1, N]` complex64 Fourier-domain filters: `J*Q` Morlet
    band-passes (highest frequency first) then the Gaussian low-pass as the
    last row. `N` is the padded length the transform will run at."""
    xi, sigma = morlet_params(J, Q, high_freq)
    psi = torch.stack([morlet_hat(N, float(x), float(s)) for x, s in zip(xi, sigma)])
    phi = gauss_hat(N, float(sigma[-1]))
    return torch.cat([psi, phi[None]]).to(torch.complex64).to(device)

# %% ../nbs/02_scattering.ipynb #d06a1415
_BANK_CACHE = {}


def get_bank(N, J, Q=1, high_freq=0.425, device=None):
    """`morlet_bank` with a cache -- the same filters are reused for every
    channel and every scattering order."""
    key = (N, J, Q, high_freq, str(device))
    if key not in _BANK_CACHE:
        _BANK_CACHE[key] = morlet_bank(N, J, Q, high_freq, device=device)
    return _BANK_CACHE[key]


def wavelet_transform(X, bank, rpad=True):
    """`[..., T]` real -> `[..., F, T]` complex: each of the `F` filters in
    `bank` (built at length `2T` if `rpad` else `T`) applied along the last
    axis by FFT."""
    T = X.shape[-1]
    Xp = torch.cat([X, X.flip(-1)], dim=-1) if rpad else X
    assert Xp.shape[-1] == bank.shape[-1], f"bank built for {bank.shape[-1]}, got {Xp.shape[-1]}"
    Xh = torch.fft.fft(Xp.to(torch.float32))
    Y = torch.fft.ifft(Xh.unsqueeze(-2) * bank)
    return Y[..., :T]

# %% ../nbs/02_scattering.ipynb #61de700d
def scattering_paths(J, Q=1, order=2):
    """Path tuples in the order `scattering` stacks them."""
    JQ = J * Q
    paths = [()]
    if order >= 1:
        paths += [(j1,) for j1 in range(JQ)]
    if order >= 2:
        paths += [(j1, j2) for j1 in range(JQ) for j2 in range(j1 + 1, JQ)]
    return paths


def scattering(X, J, Q=1, order=2, high_freq=0.425, rpad=True):
    """Wavelet scattering along the last axis. `[..., T]` real ->
    `(S, paths)` with `S` real `[..., n_paths, T]` (time axis kept) and
    `paths` from `scattering_paths`. Stays on `X`'s device."""
    assert order in (0, 1, 2)
    T = X.shape[-1]
    N = 2 * T if rpad else T
    bank = get_bank(N, J, Q, high_freq, device=X.device)
    psi, phi = bank[:-1], bank[-1]
    X = X.to(torch.float32)

    out = [wavelet_transform(X, phi[None], rpad).real]              # S0: [..., 1, T]
    if order >= 1:
        U1 = wavelet_transform(X, psi, rpad).abs()                   # [..., JQ, T]
        out.append(wavelet_transform(U1, phi[None], rpad).real[..., 0, :])
    if order >= 2:
        JQ = psi.shape[0]
        for j1 in range(JQ - 1):
            U2 = wavelet_transform(U1[..., j1, :], psi[j1 + 1:], rpad).abs()   # [..., JQ-j1-1, T]
            out.append(wavelet_transform(U2, phi[None], rpad).real[..., 0, :])
    return torch.cat(out, dim=-2), scattering_paths(J, Q, order)


def scattering_features(X, J, Q=1, order=2, log=True, eps=1e-6, **kw):
    """Time-averaged scattering coefficients: `[..., T]` -> `[..., n_paths]`.
    `log=True` (the usual choice) compresses the dynamic range across scales so
    no single path dominates a distance or correlation."""
    S, paths = scattering(X, J, Q, order, **kw)
    F = S.mean(-1)
    return (torch.log(F.clamp_min(eps)) if log else F), paths

# %% ../nbs/02_scattering.ipynb #8e256ab2
def scattering_corr(X, J, Q=1, order=2, use_abs=True, **kw):
    """`[C, T]` -> `[C, C]` correlation between channels' log-scattering
    descriptors. Drop-in for `build_corr` / `build_xcorr`."""
    F, _ = scattering_features(X, J, Q, order, log=True, **kw)
    C = torch.nan_to_num(torch.corrcoef(F), nan=0.0)
    return C.abs() if use_abs else C

# %% ../nbs/02_scattering.ipynb #0717f04f
def show_scattergram(S, paths, title, log=True, eps=1e-6, cmap="viridis", figsize=(12, 4)):
    """One channel's scattering coefficients as an image: `S` is `[n_paths, T]`."""
    import matplotlib.pyplot as plt
    Z = S.detach().cpu()
    Z = torch.log(Z.clamp_min(eps)) if log else Z
    fig, ax = plt.subplots(figsize=figsize)
    im = ax.imshow(Z.numpy(), aspect="auto", cmap=cmap, interpolation="nearest")
    ax.set_yticks(range(len(paths)))
    ax.set_yticklabels([str(p) if p else "S0" for p in paths], fontsize=7)
    ax.set_xlabel("day"); ax.set_ylabel("path (j1, j2)")
    ax.set_title(title + (" (log)" if log else ""))
    fig.colorbar(im, ax=ax, shrink=0.8)
    plt.tight_layout()
    plt.close(fig)
    return fig

# %% ../nbs/02_scattering.ipynb #11be692c
def stack_views(X, orders):
    """`[C, ...]` data + `n` orderings -> `[n, C, ...]`: the same array under
    each ordering, views stacked as the leading axis."""
    return torch.stack([X[o] for o in orders])
